### ISSUE TITLE
some log links in dart-ci and try summary appear broken

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dart_ci#104]
I don't believe this is a general issue, since some links do appear to work as usual, but I noticed a few links that did not work:

Log links here: https://dart-ci.firebaseapp.com/cl/176483/2 where a test changes from X to flaky show an error of the form
```ERROR: datastore: no such entity```

For example: https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8860711705982716064/+/steps/test_results/0/logs/new_test_failures__logs_/0 

Recent changes from flaky to X of the same test are also missing:
For example: https://dart-ci.firebaseapp.com/#showLatestFailures=false&test=corelib_2/collection_from_test&configurations=dart2js-hostasserts-linux-ia32-d8

The first log link: https://dart-ci.appspot.com/log/dart2js-strong-hostasserts-linux-ia32-d8/dart2js-hostasserts-linux-ia32-d8/11991/corelib_2/collection_from_test

Shows:
```
error: No logs found for test corelib_2/collection_from_test on build 11991 of builder dart2js-strong-hostasserts-linux-ia32-d8, configuration dart2js-hostasserts-linux-ia32-d8
```

**Comment by whesse** [comment]
There have been some breaking upstream changes to log URLs since then, and we have updated the links.  This report is no longer actionable.  We do want to improve the log links if any more broken ones are found, so reopen this issue if there are log link failures.
