### ISSUE TITLE
Cloud functions that store results to firestore don't scale to 1000 results

### ISSUE THREAD

**Issue by whesse** [dart-lang/dart_ci#46]
We had a failure in which a builder ran 3800 new tests, and the results.json was uploaded to pub/sub in 2 chunks.  Each of these chunks failed, one with a timeout after 60 seconds, and the other with a failed request and a backoff request in the error message, probably from Firestore.

Info from logs is as follows:
I see, this is from a run today, at 14:30 UTC.  I thought these results were from yesterday.  This is a failure of the system to scale, and the failure is in the log - the one failure this week was exactly then.  The overload could be in the calls to Firestore, or it could even be in the logging of cloud function info messages (print statements) to logging.  I am printing out a line for every new Firestore record created, so this is a thousand log lines in 20 seconds or so
https://pantheon.corp.google.com/logs/viewer?project=dart-ci&organizationId=433637338589&resource=cloud_function%2Ffunction_name%2FreceiveChanges%2Fregion%2Fus-central1&minLogLevel=0&expandAll=false&timestamp=2019-11-27T15:30:39.109000000Z&customFacets=&limitCustomFacetWidth=true&interval=CUSTOM&scrollTimestamp=2019-11-27T13:30:12.950000000Z&dateRangeUnbound=both&dateRangeStart=2019-11-27T13:20:39.108Z&dateRangeEnd=2019-11-27T13:40:39.108Z

William Hesse
,
7 mins
,
New
The function ran for 60 seconds, and then timed out.  So it may have been able to write all the firestore records that it tried to create correctly, but it couldn't process all 2000 within 60 seconds.  Maybe we could fix this by breaking the results.json into smaller chunks if it contains many records with "changed": true.

2019-11-27 14:31:03.091 CET
receiveChanges
860204734521613
Function execution took 60541 ms, finished with status: 'timeout'

William Hesse
,
4 mins
,
New
And that was the chunk without the error, that ran 60 seconds.  The other chunk only ran 38 seconds, and got an error, probably from Firestore:

E 2019-11-27T13:30:41.202Z receiveChanges 860204734520903 Error: The service is temporarily unavailable. Please retry with exponential backoff.
    at Http2CallStream.call.on (/srv/node_modules/@grpc/grpc-js/build/src/client.js:96:45)
    at emitOne (events.js:121:20)
    at Http2CallStream.emit (events.js:211:7)
    at process.nextTick (/srv/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9) receiveChanges 860204734520903 
  undefined
I 2019-11-27T13:30:41.259Z receiveChanges 860204734521613 Info: Adding group for co19/Language/Classes/Instance_Methods/Operators/allowed_names_t20 receiveChanges 860204734521613 
D 2019-11-27T13:30:41.286801023Z receiveChanges 860204734520903 Function execution took 38395 ms, finished with status: 'error' receiveChanges 860204734520903 
  undefined

William Hesse
,
Now
,
New
The last result updated by that chunk was  Info: Adding group for co19/LanguageFeatures/regression/33805_t02/02

I will file all this info in a bug.  I will stop the printing of a log message for every group, after a certain limit per run.  I will look into detecting this failure result from Firestore (if that is where it came from), and will consider implementing a backoff, but that won't really help with the 60 second limit.  I think we have right now a failure that only occurs if we have more than 500 new tests or failures on a builder, and maybe only if we have more than 2000.

**Comment by whesse** [comment]
Actually, the chunks were each almost 10,000 results.  But I don't think more than 1000 got successfully processed from either of them.

**Comment by athomas** [comment]
https://firebase.google.com/docs/firestore/quotas#writes_and_transactions we might be hitting one of these limits.

**Comment by whesse** [comment]
Note that we still send all the flaky changed results, even though they are also ignored by the Firestore processing.

**Comment by whesse** [comment]
There was a failure, with most chunks timing out in the cloud functions, when a trybot sent 5500 crash results to cloud functions in 55 chunks.  A solution to this would be to send the changes in even smaller chunks when there are a very large number of them,  and perhaps to increase the delay between chunks.

We could also consider whether to avoid sending this many changes from a try job, and the long-term fix is to move processing off of cloud functions, and/or to compress multiple identical new results into a single summary record and process that.

Reopening the issue, proposing the immediate fix of reducing the number of results per chunk even further if there are thousands of them.

**Comment by whesse** [comment]
The change to process only 50 results in a chunk instead of 100 has landed, and testing of it on dart-ci-staging shows that it fixes the problem, at least mostly.  All chunks are not processed, taking 25 to 45 seconds, while they timed out if they were bigger, with 100 results.  There seems to be no overloading or contention, since the chunks are spaced out at 2 second intervals.

Other long-term fixes include adding better logging to the cloud functions, so we can detect reasons for slowdowns, and moving the results processing off of cloud functions onto the builders or another more stable platform.
