### ISSUE TITLE
Reduce logging from cloud functions

### ISSUE THREAD

**Issue by whesse** [dart-lang/dart_ci#47]
Each run of the cloud function produces many lines of logs, most of which are uninformative: 0 new builds stored, for example.

Don't print out statistics that are 0, and don't print out a line for every new failure record created, because sometimes we create 10,000 of them.  This may help with the scalability issue in #46 .

**Comment by athomas** [comment]
I don't see excessive logs right now, so I'm assuming this was fixed.
