### ISSUE TITLE
Commits/blamelists should have permanent links

### ISSUE THREAD

**Issue by sortie** [dart-lang/dart_ci#50]
There should be a way to permanently link to the blamelists for a given commit. Otherwise it will not be possible to refer to what transpired, such as from github.

**Comment by whesse** [comment]
I'm not sure what is meant here.  Different builders have different blamelists.  A commit by definition is not a blamelist.  There is an issue #62 filed to allow result feed links with a blamelist in their filter, which will only show results from builds intersecting that blamelist.
A link to github showing a commit range has the form 
https://github.com/dart-lang/sdk/compare/c359b5943a52b525198bb094a731d06c2a7fe08f...da1e42a11c2663e71e9c967218b381cd3943e43a
and lists commits not including the start, but including the end.
