### ISSUE TITLE
The "Aggregated test results" link in Gerrit should open in a new window

### ISSUE THREAD

**Issue by nshahan** [dart-lang/dart_ci#55]
All of the other links related to viewing test results open in a new window/tab and I have been trained to expect it. I find that I commonly close the tab that contains the aggregated results and then wonder where my gerrit review went.

In my opinion this link should have the same behavior as clicking on a trybot to see the details of the results.

**Comment by whesse** [comment]
This is fixed by adding target="_blank" rel="noopener" to the html anchor.  This is a change in internal Google software, CL has been created.

**Comment by athomas** [comment]
Closing, this works now so the fix is deployed.
