### ISSUE TITLE
Revert of new failing test leaves unapproved test

### ISSUE THREAD

**Issue by athomas** [dart-lang/dart_ci#63]
If a commit adding a new failing test is reverted, the failure remains active despite the test no longer running which keeps the builds red.

**Comment by whesse** [comment]
The planned fix for this is to:
Add "not run" records to results.json for tests that were in the previous results.json but not in the new results.  So, just like the "new test" changed results for new tests, we will have "not run" changed results for tests that stop running.  The next build will see "not run" in the previous build, and if the test is still not running, will emit no record for it.  In the weird case that it runs again, after a single build without the result, we should really try and fetch the results.json for the build before that, and copy its status.  But that isn't needed immediately.

Then the "not run" records will be added to the firestore database, and reported as (green?) changes on the results feed.  They will also become the "active" result for the test, and therefore cancel any active failure for it.  The failure will then disappear from "active failures".

**Comment by whesse** [comment]
This fix was landed in https://dart-review.googlesource.com/c/sdk/+/134324
This fix is also issue #72
