### ISSUE TITLE
Aggregated test results page needs a loading indicator

### ISSUE THREAD

**Issue by nshahan** [dart-lang/dart_ci#66]
I have found that sometimes it takes a long time for the failures to appear on the aggregated test results page linked from a gerrit review. While they are loading I see the message "No changed test results" which makes me think there will be nothing. This should be a loading indicator of some kind before they are loaded so I don't close the window too soon.

For example try looking at https://dart-ci.firebaseapp.com/cl/134089/1 but don't close it too soon. 😄

**Comment by athomas** [comment]
Fixed by https://dart-review.googlesource.com/c/dart_ci/+/140283.
