### ISSUE TITLE
feed UI: add option to select only my team

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dart_ci#68]
currently there are options to filter by team, but to select a single team one needs to unselect all others. It would be great to have a "only" link to select only my team.

**Comment by whesse** [comment]
As part of adding a "configurations=" option to the filter URL fragment, the "configuration_groups" fragment and UI have been changed to be empty when the filter is inactive (all groups selected), so clicking on a single group will turn on the filter and enable just that group.  This solves the problem.
