### ISSUE TITLE
use submitted pre-approvals on subsequent try jobs?

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dart_ci#74]
A few team members were puzzled today by a failure on the bots.

It appears like:
* this CL: https://dart-review.googlesource.com/c/sdk/+/135492 changed a test from being a multi-test to be an error test. The CL run the front-end-nnbd-linux-release-x64 builder and approved the new failures.
* later our dry-runs showed this builder as failing on that test.

It took sometime to realize it was not related to our changes but we aren't sure why it is happening. Are the try-jobs only seeing approvals at `origin/base` after the fleet of bots catch up with the commits? If so, would it be possible to do something to reduce this inconsistent state gap?

**Comment by sigmundch** [comment]
Just to give an idea of the gap, the original CL landed 4 hours ago and we still see the failures happening on our dry runs

**Comment by whesse** [comment]
Yes, this is our highest priority right now, working on it.

**Comment by whesse** [comment]
This is complete. Errors that are approved on CLs, where the CL has landed but the CI has not run it yet, are filtered out from error reports on later tryjobs that are based on the landed CL, but don't have its baseline results yet.
